name: ls test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: DEBUG - List available configs
      run: |
        # Проверим, в какой папке мы работаем (должна быть папка ядра)
        pwd

        echo "--- list"
        ls -R

        echo "---- list2"
        ls -R ..
        echo "---- list3"
        ls -R ../..
        # Проверим содержимое папки configs
        echo "--- Listing arch/arm64/configs/ ---"
        ls -R arch/arm64/configs/
        
        # Если ты используешь конструкцию if [ -d "kernel" ]; then cd kernel; fi
        # то ls будет выполняться из корня репозитория, а не из папки kernel.
        # Поэтому проверим и там:
        if [ -d "kernel" ]; then 
          echo "--- Listing kernel/arch/arm64/configs/ ---"
          ls -R kernel/arch/arm64/configs/
        fi
